worker_processes 1;
error_log /dev/null;
pid /tmp/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log off;

    server {
        listen 80;
        server_name _;

        location = /generate_204 {
            return 204;
        }

        location / {
            return 204;
        }
    }
}
